# Análise Exploratória de Dados - Supermarket Sales

Dataset de um supermercado com 1000 transações,
acerca de três filiais em diferentes cidades.
- O que é um dataset?
Dataset é um conjunto de dados organizados. Dentro do projeto será utilizado para análise.
- O que será utilizado?
**Linguagem:** Python
**Biblioteca:** Pandas

## 1. importação e Carregamento dos Dados

In [27]:

import pandas as pd

df = pd.read_csv("../data/supermarket_sales.csv")
df.head(10)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,C,Naypyitaw,Normal,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38,Ewallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,A,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,1/10/2019,17:15,Credit card,72.52,4.761905,3.6260,7.2
9,692-92-5582,B,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2/20/2019,13:27,Credit card,164.52,4.761905,8.2260,5.9

## 2. Tradução das Colunas

As colunas foram renomeadas para facilitar a leitura e interpretação durante a análise.

In [28]:
df = df.rename(columns={
    "Invoice ID": "id_fatura",
    "Branch": "filial",
    "City":"cidade",
    "Customer type": "tipo_cliente",
    "Gender": "genero",
    "Product line": "categoria_produto",
    "Unit price": "preco_unidade",
    "Quantity": "quantidade",
    "Tax 5%": "imposto",
    "Total": "faturamento",
    "Date": "data",
    "Time": "hora",
    "Payment":"pagamento",
    "cogs": "custo_produtos_vendidos",
    "gross margin percentage": "percentual_margem_bruta",
    "gross income": "lucro_bruto",
    "Rating": "avaliacao"
})

df.columns

Index(['id_fatura', 'filial', 'cidade', 'tipo_cliente', 'genero',
       'categoria_produto', 'preco_unidade', 'quantidade', 'imposto',
       'faturamento', 'data', 'hora', 'pagamento', 'custo_produtos_vendidos',
       'percentual_margem_bruta', 'lucro_bruto', 'avaliacao'],
      dtype='object')

In [29]:
pagamento_map = {
    "Cash": "dinheiro",
    "Ewallet": "carteira_digital",
    "Credit card": "cartao_credito"
}

df["pagamento"] = df["pagamento"].map(pagamento_map)

print(df["pagamento"].unique())

['carteira_digital' 'dinheiro' 'cartao_credito']

## 3. Tradução dos Valores Categóricos

Os valores foram traduzidos para manter a consistência com os nomes das colunas.

In [30]:
map_categoria_produto = {
    "Health and beauty": "saude_beleza",
    "Electronic accessories": "acessorios_eletronicos",
    "Home and lifestyle": "casa_estilo_de_vida",
    "Sports and travel": "esportes_viagem",
    "Food and beverages": "alimentos_bebidas",
    "Fashion accessories": "acessorios_moda"
    }
df["categoria_produto"] = df["categoria_produto"].map(map_categoria_produto)

print(df["categoria_produto"].unique())

['saude_beleza' 'acessorios_eletronicos' 'casa_estilo_de_vida'
 'esportes_viagem' 'alimentos_bebidas' 'acessorios_moda']

In [31]:
map_genero = {
    "Female": "feminino",
    "Male": "masculino"
}

df["genero"] = df["genero"].map(map_genero)

print(df["genero"].unique())

['feminino' 'masculino']

In [32]:
map_tipo_cliente = {
    "Member": "membro",
    "Normal": "normal"
}

df["tipo_cliente"] = df["tipo_cliente"].map(map_tipo_cliente)

print(df["tipo_cliente"].unique())

['membro' 'normal']

Valores renomeados:

In [33]:
df.head()

,id_fatura,filial,cidade,tipo_cliente,genero,categoria_produto,preco_unidade,quantidade,imposto,faturamento,data,hora,pagamento,custo_produtos_vendidos,percentual_margem_bruta,lucro_bruto,avaliacao
0,750-67-8428,A,Yangon,membro,feminino,saude_beleza,74.69,7,26.1415,548.9715,1/5/2019,13:08,carteira_digital,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,normal,feminino,acessorios_eletronicos,15.28,5,3.8200,80.2200,3/8/2019,10:29,dinheiro,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,normal,masculino,casa_estilo_de_vida,46.33,7,16.2155,340.5255,3/3/2019,13:23,cartao_credito,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,membro,masculino,saude_beleza,58.22,8,23.2880,489.0480,1/27/2019,20:33,carteira_digital,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,normal,masculino,esportes_viagem,86.31,7,30.2085,634.3785,2/8/2019,10:37,carteira_digital,604.17,4.761905,30.2085,5.3

## 4. Faturamento por Filial

Ordem decrescente das filiais que mais faturaram.

In [34]:
total_filiais = df.groupby("filial" )["faturamento"].sum()
total_filiais.sort_values(ascending=False, ignore_index=False)

filial
C    110568.7065
A    106200.3705
B    106197.6720
Name: faturamento, dtype: float64

A filial **C** lidera o ranking de faturamento total, com pouca distância das filiais **A** e **B**.

## 5. Faturamento de Produtos por Categoria 

Ordem decrescente do faturamento total por categoria de produto

In [35]:
total_categoria_produto = df.groupby("categoria_produto")["faturamento"].sum()
total_categoria_produto.sort_values(ascending=False)

categoria_produto
alimentos_bebidas         56144.8440
esportes_viagem           55122.8265
acessorios_eletronicos    54337.5315
acessorios_moda           54305.8950
casa_estilo_de_vida       53861.9130
saude_beleza              49193.7390
Name: faturamento, dtype: float64

A categoria **alimentos e bebidas** lidera o faturamento, **Saúde e beleza** é a menos rentável, com aproximadamente $7.000 de diferença.

## 6. Média do Valor de Compras por Método de Pagamento

Comparação do ticket médio entre as diferentes formas de pagamento.

In [36]:
media_metodo_pagamento = df.groupby("pagamento")["faturamento"].mean()
media_metodo_pagamento.sort_values(ascending=False)

pagamento
dinheiro            326.181890
cartao_credito      324.009878
carteira_digital    318.820600
Name: faturamento, dtype: float64

A diferença entre os métodos é baixa, indicando que a forma de pagamento não interfere no valor final da compra.

## 7. Faturamento por Filial e Categoria de Produto

Faturamento total, agrupado por filial e categoria, em ordem decrescente.

In [37]:
faturamento_filiais = df.groupby(["filial", "categoria_produto"])["faturamento"].sum()
faturamento_filiais.sort_values(ascending=False)

filial  categoria_produto
C       alimentos_bebidas         23766.8550
A       casa_estilo_de_vida       22417.1955
C       acessorios_moda           21560.0700
B       esportes_viagem           19988.1990
        saude_beleza              19980.6600
A       esportes_viagem           19372.6995
C       acessorios_eletronicos    18968.9745
A       acessorios_eletronicos    18317.1135
B       casa_estilo_de_vida       17549.1645
A       alimentos_bebidas         17163.1005
B       acessorios_eletronicos    17051.4435
C       saude_beleza              16615.3260
B       acessorios_moda           16413.3165
A       acessorios_moda           16332.5085
C       esportes_viagem           15761.9280
B       alimentos_bebidas         15214.8885
C       casa_estilo_de_vida       13895.5530
A       saude_beleza              12597.7530
Name: faturamento, dtype: float64

A filial **C** se apresenta como a líder no faturamento por categoria tendo **alimentos e bebidas** como principal destaque.